### ISSUE TITLE
页面最顶部的搜索框可以搜到什么东西？

### ISSUE THREAD

**Issue by ghost** [devinzhang/teemeet.com#25]
搜到的应该是聚会和小组，但是现在teemeet上这个页好像没实现

**Comment by lcnphp** [comment]
ʽе⣬ťĳdiv㵲סˣ㲻

2011/12/5 wannianchuan <
reply@reply.github.com

**Comment by ghost** [comment]
这个地方的搜索和首页右侧的搜索搜到的东西是一样的。原来只在模板里加了个form，未实行功能，现在功能已实现，浏览器兼容性也已调整。
